spring.application.name=Chat-Application

# =========================
# DATABASE
# =========================


spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/chat_service?useSSL=false&serverTimezone=Asia/Kolkata}

spring.datasource.username=${DB_USERNAME:root}

spring.datasource.password=${DB_PASSWORD:Root@123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# SERVER
# =========================
server.address=0.0.0.0
server.port=8080


# =========================
# JWT
# =========================

jwt.secret=${JWT_SECRET:SoftmintProjectSecretKeyForJWTAuthentication123456789}
jwt.expiration=86400000